### PR TITLE
delete all duplicate empty blanks

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <764524258@qq.com>

### CODE REVIEW

**Review by a180285 — APPROVED** [review]
LGTM, code style is great.

**Comment by daixiang0** [comment]
any update?

**Comment by daixiang0** [comment]
any update?

**Comment by daixiang0** [comment]
@a180285 any update?

**Comment by daixiang0** [comment]
@a180285 hi, any update?

**Comment by daixiang0** [comment]
@a180285 hi, any update?

**Comment by a180285** [comment]
@daixiang0 I have no access to approve~~ I also want this request being merged

**Comment by daixiang0** [comment]
any update?

**Comment by daixiang0** [comment]
any update?

**Comment by revl-ca** [comment]
The project has been abandoned

**Comment by daixiang0** [comment]
@revl-ca change to which repo?

**Comment by daixiang0** [comment]
https://blogs.vmware.com/cloudnative/2019/02/05/welcoming-heptio-open-source-projects-to-vmware/
The repo has been abandoned indeed.

**Pull request closed without merging**
