### PR TITLE
Adds chocolatey on windows section to readme

### PR DESCRIPTION
**Pull request by stefanhenseler**
Hi, I've created a [choco package](https://chocolatey.org/packages/ksonnet) and will maintain it moving forward. I would like to add a hint to the readme for all the Windows users of ksonnet. I've also created a Zapier Zap to automatically update the choco package on every release created in ksonnet/ksonnet.

### CODE REVIEW

**Comment by bryanl** [comment]
Hello,

Thanks for this package. Would you mind if the ksonnet team took this over? We'd hook it into our build pipeline and would not require the Zapier integration?

**Comment by synax** [comment]
Hi, this would even be better. How would you like to do this? Do you want to create a repo and I'll hand over the package to you? I need to check how I can transfer ownership of the chocolatey package to you. I guess you'd have to create a chocolatey account first?

**Comment by bryanl** [comment]
This item is still open. We are currently working out our 0.12 release and will revisit afterwards.

**Comment by stefanhenseler** [comment]
ksonnet will be discontinued, so I think this issue can be closed.

**Pull request closed without merging**
